### ISSUE TITLE
Initial matrix prior to iterating

### ISSUE THREAD

**Issue by tfirzli** [mayer79/missRanger#20]
Hello-

Love the package, I was curious if there is a way to initialize the matrix to something other than predictive mean matching? For example, instead of using predictive mean matching, say using zero imputation, min imputation or an alternative method. I am working with left truncated data where missing data is likely very close to zero, so I wondered if there was a way to do this?

**Comment by mayer79** [comment]
It is not possible, I fear. However, initialization is not too important: it is only required if each variable has missing values. In that case, the column with the fewest missings is indeed filled by unconditional PMM. Then, this variable is used to fill the gaps in the column with the second fewest missings etc. until all variables are complete. Then, the actual chaining algorithm starts.

The big assumption behind (almost?) any imputation algorithm is non-informative missingness. In your situation, this seems to be violated ("if value is missing, then it is probably close to 0"). So even if you would be able to initialize this particular left truncated column with zeros, the subsequent imputation process would shift the values away from 0 based on conditional association to other columns.

Since you already know that missing values should be very close to zero, manual imputation might be the best option. However, I don't know enough about your specific situation to give a well-founded suggestion in this respect.
