### ISSUE TITLE
Allow 'mtry'

### ISSUE THREAD

**Issue by tslumley** [mayer79/missRanger#22]
Would you be interested in a patch to allow users to adjust `mtry`?  It's a major tuning parameter for random forests, so I think it would help.  What I have done is to add a `mtry_rule` argument, which is a function taking an vector of variable names as input and returning a value of `mtry`, called with `union(v,completed)`.  The current rule is roughly

```
function(x) floor(sqrt(length(x)-1)))
```

and I've tried others such as

```
function(x) min(5, length(x)-1)
```

**Comment by mayer79** [comment]
Your approach is very good. `ranger` actually already allows `mtry` to be a function of the number of covariables, so we only have to stick to this one.

E.g.
```
ranger(Sepal.Length ~ ., data = iris, mtry = function(x) x%/%2) 
```
gives mtry = 2.

Interestingly, the default passed to the internal C++ interface is `mtry=0` and is internally set to something like floor(sqrt(m)). However, an `mtry` function is not allowed to return 0.

Suggestion 1: We add the argument `mtry = NULL` and allow only the "function" interface of ranger otherwise. 

Suggestion 2: Same but we allow also numeric values for `mtry`, e.g. 1. When calling `ranger`, the value is capped from above with the number of covariables. We could mention in the argument description something like "since the number of covariables might change during the process, consider passing a single argument function of the number of covariables, e.g. `function(m) = m %/% 3`.

**Comment by mayer79** [comment]
Now in master branch.
