### ISSUE TITLE
Adding out-of-bag errors and convergence monitoring

### ISSUE THREAD

**Issue by bgall** [mayer79/missRanger#28]
Two enhancements would be very useful:

1. Add an argument to return the out-of-bag (OOB) prediction error (on a variable-by variable basis), a la [missForest](https://github.com/stekhoven/missForest). If argument is `T`, could return a list with data in one element and error in others. Preferably variablewise. Right now only the average is returned.

2. Some way of monitoring convergence like `mice`'s plots of the chained values.

**Comment by mayer79** [comment]
Thanks for these hints. 

1. I think the first point is captured by the `returnOOB` argument. It attaches the attribute `oob` to the resulting dataset with the OOB errors of the final round. I am aware this interface is not ideal. Nowadays, I'd definitively return a list with class "missRanger" and a couple of methods, like e.g. in my `outForest` outlier detection package. Maybe I can go into the direction you are proposing and go for an argument `return_data_only = TRUE` for the current behaviour and for a nice "missRanger" object otherwise.

2. Good idea. I will consider adding this feature to the next release.

**Comment by mayer79** [comment]
Finally solved via https://github.com/mayer79/missRanger/pull/55
